version: '3'

networks:
  i_see_cubes_main:
    driver: bridge

services:

#
#  cabin_db:
#    image: mysql:8.0.27
#    volumes:
#      - "./.mysql-data/db:/var/lib/mysql"
#    restart: always
#    ports:
#      - 3306:3306
#    networks:
#      - creditto_main
#    environment:
#      MYSQL_ROOT_PASSWORD: 123456
#      MYSQL_DATABASE: sys


  chat_messenger:
    image: chat_messenger_server:latest
    build: ./server_side
    restart: always
    ports:
      - "5000:5000"
#    depends_on:
#      - cabin_db

    networks:
      - i_see_cubes_main
    environment:
      -KEEP_ALIVE_LOGGING=10
      -OPENAI_API_KEY=""
#      - SQL_HOST=cabin_db
#      - SQL_PORT=3306
#      - SQL_USER=root
#      - SQL_PASSWORD=123456
#      - WAIT_BEFORE_TIMEOUT=15
#      - MYSQL_DB_WARMUP_DELAY=60