version: '3'

networks:
  i_see_cubes_main:
    driver: bridge

volumes:
  db:
    driver: local

  redis_data:

services:

  postgres:
      image: postgres:14.1-alpine
      restart: always
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      ports:
        - '5432:5432'
      volumes:
        - db:/var/lib/postgresql/data
      networks:
        - i_see_cubes_main

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - i_see_cubes_main


#  chat_messenger:
#      image: chat_messenger_server:latest
#      build: ./server_side
#      restart: always
#      ports:
#        - 5000:5000
#      depends_on:
#        - postgres
#      networks:
#        - i_see_cubes_main
#      environment:
#        KEEP_ALIVE_LOGGING: 10
#        OPENAI_API_KEY: 0
#        SQL_HOST: iseecubes_postgres_1
#        SQL_USER: postgres
#        SQL_PASSWORD: postgres
#        SQL_DB_NAME: chat_db
#        REDIS_HOST: iseecubes_redis_1
#        WAIT_BEFORE_TIMEOUT: 15
#        POSTGRES_DB_WARMUP_DELAY: 60


